#############################################################################
# Makefile for building: TexSketch
# Generated by qmake (3.1) (Qt 5.9.1)
# Project:  TexSketch.pro
# Template: app
# Command: /Users/albertolascala/Qt/5.9.1/clang_64/bin/qmake -o Makefile TexSketch.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -Iui -Iglm -Ishaders -Iimages -I../Qt/5.9.1/clang_64/lib/QtOpenGL.framework/Headers -I../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -Imoc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -Iui -I../Qt/5.9.1/clang_64/mkspecs/macx-clang -F/Users/albertolascala/Qt/5.9.1/clang_64/lib
QMAKE         = /Users/albertolascala/Qt/5.9.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/albertolascala/Qt/5.9.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/albertolascala/Qt/5.9.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TexSketch1.0.0
DISTDIR = /Users/albertolascala/TexSketch/obj/TexSketch1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/albertolascala/Qt/5.9.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/albertolascala/Qt/5.9.1/clang_64/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/MainWindow.cpp \
		src/GLWindow.cpp \
		src/Mesh.cpp \
		src/Shader.cpp \
		src/Camera.cpp \
		src/TrackballCamera.cpp moc/moc_MainWindow.cpp \
		moc/moc_GLWindow.cpp
OBJECTS       = obj/main.o \
		obj/MainWindow.o \
		obj/GLWindow.o \
		obj/Mesh.o \
		obj/Shader.o \
		obj/Camera.o \
		obj/TrackballCamera.o \
		obj/moc_MainWindow.o \
		obj/moc_GLWindow.o
DIST          = ../Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.9.1/clang_64/mkspecs/qdevice.pri \
		../Qt/5.9.1/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.9.1/clang_64/mkspecs/common/unix.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/mac.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/macx.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/clang.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.9.1/clang_64/mkspecs/qconfig.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/qt.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/resources.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/moc.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/uic.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/lex.prf \
		TexSketch.pro include/MainWindow.h \
		include/GLWindow.h \
		include/Mesh.h \
		include/Shader.h \
		include/Camera.h \
		include/TrackballCamera.h src/main.cpp \
		src/MainWindow.cpp \
		src/GLWindow.cpp \
		src/Mesh.cpp \
		src/Shader.cpp \
		src/Camera.cpp \
		src/TrackballCamera.cpp
QMAKE_TARGET  = TexSketch
DESTDIR       = 
TARGET        = TexSketch

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui/ui_MainWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TexSketch.pro ../Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf ../Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.9.1/clang_64/mkspecs/qdevice.pri \
		../Qt/5.9.1/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.9.1/clang_64/mkspecs/common/unix.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/mac.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/macx.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/clang.conf \
		../Qt/5.9.1/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.9.1/clang_64/mkspecs/qconfig.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/qt.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/resources.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/moc.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/uic.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.9.1/clang_64/mkspecs/features/lex.prf \
		TexSketch.pro \
		../Qt/5.9.1/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/QtGui.prl \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile TexSketch.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf:
../Qt/5.9.1/clang_64/mkspecs/qdevice.pri:
../Qt/5.9.1/clang_64/mkspecs/features/device_config.prf:
../Qt/5.9.1/clang_64/mkspecs/common/unix.conf:
../Qt/5.9.1/clang_64/mkspecs/common/mac.conf:
../Qt/5.9.1/clang_64/mkspecs/common/macx.conf:
../Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf:
../Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf:
../Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../Qt/5.9.1/clang_64/mkspecs/common/clang.conf:
../Qt/5.9.1/clang_64/mkspecs/common/clang-mac.conf:
../Qt/5.9.1/clang_64/mkspecs/qconfig.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf:
../Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf:
../Qt/5.9.1/clang_64/mkspecs/macx-clang/qmake.conf:
../Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf:
../Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf:
../Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf:
../Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf:
../Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf:
../Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf:
../Qt/5.9.1/clang_64/mkspecs/features/default_post.prf:
../Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf:
../Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf:
../Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf:
../Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf:
../Qt/5.9.1/clang_64/mkspecs/features/qt.prf:
../Qt/5.9.1/clang_64/mkspecs/features/resources.prf:
../Qt/5.9.1/clang_64/mkspecs/features/moc.prf:
../Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf:
../Qt/5.9.1/clang_64/mkspecs/features/uic.prf:
../Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf:
../Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf:
../Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf:
../Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf:
../Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf:
../Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf:
../Qt/5.9.1/clang_64/mkspecs/features/yacc.prf:
../Qt/5.9.1/clang_64/mkspecs/features/lex.prf:
TexSketch.pro:
../Qt/5.9.1/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
../Qt/5.9.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../Qt/5.9.1/clang_64/lib/QtGui.framework/QtGui.prl:
../Qt/5.9.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile TexSketch.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/MainWindow.h include/GLWindow.h include/Mesh.h include/Shader.h include/Camera.h include/TrackballCamera.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/MainWindow.cpp src/GLWindow.cpp src/Mesh.cpp src/Shader.cpp src/Camera.cpp src/TrackballCamera.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/MainWindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: ../Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc/moc_predefs.h ../Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_MainWindow.cpp moc/moc_GLWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_MainWindow.cpp moc/moc_GLWindow.cpp
moc/moc_MainWindow.cpp: ../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		include/GLWindow.h \
		include/Shader.h \
		include/TrackballCamera.h \
		include/Camera.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/detail/func_matrix.hpp \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/detail/func_exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/exponential.hpp \
		glm/common.hpp \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/matrix.hpp \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/matrix_transform.inl \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/quaternion.inl \
		glm/gtc/quaternion_simd.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QEvent \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		include/Mesh.h \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		glm/ext.hpp \
		glm/gtc/bitfield.hpp \
		glm/gtc/bitfield.inl \
		glm/gtc/color_space.hpp \
		glm/gtc/color_space.inl \
		glm/gtc/epsilon.hpp \
		glm/gtc/epsilon.inl \
		glm/gtc/functions.hpp \
		glm/gtc/functions.inl \
		glm/gtc/integer.hpp \
		glm/gtc/integer.inl \
		glm/gtc/matrix_access.hpp \
		glm/gtc/matrix_access.inl \
		glm/gtc/matrix_integer.hpp \
		glm/gtc/matrix_inverse.hpp \
		glm/gtc/matrix_inverse.inl \
		glm/gtc/noise.hpp \
		glm/detail/_noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/packing.hpp \
		glm/gtc/packing.inl \
		glm/gtc/random.hpp \
		glm/gtc/random.inl \
		glm/gtc/reciprocal.hpp \
		glm/gtc/reciprocal.inl \
		glm/gtc/round.hpp \
		glm/gtc/round.inl \
		glm/gtc/ulp.hpp \
		glm/gtc/ulp.inl \
		glm/gtc/type_aligned.hpp \
		glm/gtx/associated_min_max.hpp \
		glm/gtx/associated_min_max.inl \
		glm/gtx/bit.hpp \
		glm/gtx/bit.inl \
		glm/gtx/closest_point.hpp \
		glm/gtx/closest_point.inl \
		glm/gtx/color_space.hpp \
		glm/gtx/color_space_YCoCg.hpp \
		glm/gtx/color_space_YCoCg.inl \
		glm/gtx/compatibility.hpp \
		glm/gtx/compatibility.inl \
		glm/gtx/component_wise.hpp \
		glm/gtx/component_wise.inl \
		glm/gtx/euler_angles.hpp \
		glm/gtx/euler_angles.inl \
		glm/gtx/extend.hpp \
		glm/gtx/extend.inl \
		glm/gtx/extended_min_max.hpp \
		glm/gtx/extended_min_max.inl \
		glm/gtx/fast_exponential.hpp \
		glm/gtx/fast_exponential.inl \
		glm/gtx/fast_square_root.hpp \
		glm/gtx/fast_square_root.inl \
		glm/gtx/fast_trigonometry.hpp \
		glm/gtx/fast_trigonometry.inl \
		glm/gtx/gradient_paint.hpp \
		glm/gtx/optimum_pow.hpp \
		glm/gtx/optimum_pow.inl \
		glm/gtx/gradient_paint.inl \
		glm/gtx/handed_coordinate_space.hpp \
		glm/gtx/handed_coordinate_space.inl \
		glm/gtx/integer.hpp \
		glm/gtx/intersect.hpp \
		glm/gtx/vector_query.hpp \
		glm/gtx/vector_query.inl \
		glm/gtx/intersect.inl \
		glm/gtx/log_base.hpp \
		glm/gtx/log_base.inl \
		glm/gtx/matrix_cross_product.hpp \
		glm/gtx/matrix_cross_product.inl \
		glm/gtx/matrix_interpolation.hpp \
		glm/gtx/matrix_interpolation.inl \
		glm/gtx/matrix_major_storage.hpp \
		glm/gtx/matrix_major_storage.inl \
		glm/gtx/matrix_operation.hpp \
		glm/gtx/matrix_operation.inl \
		glm/gtx/matrix_query.hpp \
		glm/gtx/matrix_query.inl \
		glm/gtx/mixed_product.hpp \
		glm/gtx/mixed_product.inl \
		glm/gtx/norm.hpp \
		glm/gtx/quaternion.hpp \
		glm/gtx/norm.inl \
		glm/gtx/normal.hpp \
		glm/gtx/normal.inl \
		glm/gtx/normalize_dot.hpp \
		glm/gtx/normalize_dot.inl \
		glm/gtx/number_precision.hpp \
		glm/gtx/number_precision.inl \
		glm/gtx/orthonormalize.hpp \
		glm/gtx/orthonormalize.inl \
		glm/gtx/perpendicular.hpp \
		glm/gtx/projection.hpp \
		glm/gtx/projection.inl \
		glm/gtx/perpendicular.inl \
		glm/gtx/polar_coordinates.hpp \
		glm/gtx/polar_coordinates.inl \
		glm/gtx/raw_data.hpp \
		glm/gtx/raw_data.inl \
		glm/gtx/rotate_vector.hpp \
		glm/gtx/transform.hpp \
		glm/gtx/transform.inl \
		glm/gtx/rotate_vector.inl \
		glm/gtx/spline.hpp \
		glm/gtx/spline.inl \
		glm/gtx/std_based_type.hpp \
		glm/gtx/std_based_type.inl \
		glm/gtx/transform2.hpp \
		glm/gtx/transform2.inl \
		glm/gtx/vector_angle.hpp \
		glm/gtx/vector_angle.inl \
		glm/gtx/wrap.hpp \
		glm/gtx/wrap.inl \
		glm/gtx/scalar_multiplication.hpp \
		glm/gtx/range.hpp \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		include/MainWindow.h \
		moc/moc_predefs.h \
		../Qt/5.9.1/clang_64/bin/moc
	/Users/albertolascala/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/Users/albertolascala/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/albertolascala/TexSketch -I/Users/albertolascala/TexSketch/include -I/Users/albertolascala/TexSketch/ui -I/Users/albertolascala/TexSketch/glm -I/Users/albertolascala/TexSketch/shaders -I/Users/albertolascala/TexSketch/images -I/Users/albertolascala/Qt/5.9.1/clang_64/lib/QtOpenGL.framework/Headers -I/Users/albertolascala/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/albertolascala/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/albertolascala/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/usr/local/include/c++/6.4.0 -I/usr/local/include/c++/6.4.0/x86_64-pc-linux-gnu -I/usr/local/include/c++/6.4.0/backward -I/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include-fixed -I/usr/include -F/Users/albertolascala/Qt/5.9.1/clang_64/lib include/MainWindow.h -o moc/moc_MainWindow.cpp

moc/moc_GLWindow.cpp: include/Shader.h \
		include/TrackballCamera.h \
		include/Camera.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/detail/func_matrix.hpp \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/detail/func_exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/exponential.hpp \
		glm/common.hpp \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/matrix.hpp \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/matrix_transform.inl \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/quaternion.inl \
		glm/gtc/quaternion_simd.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QEvent \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		include/Mesh.h \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		glm/ext.hpp \
		glm/gtc/bitfield.hpp \
		glm/gtc/bitfield.inl \
		glm/gtc/color_space.hpp \
		glm/gtc/color_space.inl \
		glm/gtc/epsilon.hpp \
		glm/gtc/epsilon.inl \
		glm/gtc/functions.hpp \
		glm/gtc/functions.inl \
		glm/gtc/integer.hpp \
		glm/gtc/integer.inl \
		glm/gtc/matrix_access.hpp \
		glm/gtc/matrix_access.inl \
		glm/gtc/matrix_integer.hpp \
		glm/gtc/matrix_inverse.hpp \
		glm/gtc/matrix_inverse.inl \
		glm/gtc/noise.hpp \
		glm/detail/_noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/packing.hpp \
		glm/gtc/packing.inl \
		glm/gtc/random.hpp \
		glm/gtc/random.inl \
		glm/gtc/reciprocal.hpp \
		glm/gtc/reciprocal.inl \
		glm/gtc/round.hpp \
		glm/gtc/round.inl \
		glm/gtc/ulp.hpp \
		glm/gtc/ulp.inl \
		glm/gtc/type_aligned.hpp \
		glm/gtx/associated_min_max.hpp \
		glm/gtx/associated_min_max.inl \
		glm/gtx/bit.hpp \
		glm/gtx/bit.inl \
		glm/gtx/closest_point.hpp \
		glm/gtx/closest_point.inl \
		glm/gtx/color_space.hpp \
		glm/gtx/color_space_YCoCg.hpp \
		glm/gtx/color_space_YCoCg.inl \
		glm/gtx/compatibility.hpp \
		glm/gtx/compatibility.inl \
		glm/gtx/component_wise.hpp \
		glm/gtx/component_wise.inl \
		glm/gtx/euler_angles.hpp \
		glm/gtx/euler_angles.inl \
		glm/gtx/extend.hpp \
		glm/gtx/extend.inl \
		glm/gtx/extended_min_max.hpp \
		glm/gtx/extended_min_max.inl \
		glm/gtx/fast_exponential.hpp \
		glm/gtx/fast_exponential.inl \
		glm/gtx/fast_square_root.hpp \
		glm/gtx/fast_square_root.inl \
		glm/gtx/fast_trigonometry.hpp \
		glm/gtx/fast_trigonometry.inl \
		glm/gtx/gradient_paint.hpp \
		glm/gtx/optimum_pow.hpp \
		glm/gtx/optimum_pow.inl \
		glm/gtx/gradient_paint.inl \
		glm/gtx/handed_coordinate_space.hpp \
		glm/gtx/handed_coordinate_space.inl \
		glm/gtx/integer.hpp \
		glm/gtx/intersect.hpp \
		glm/gtx/vector_query.hpp \
		glm/gtx/vector_query.inl \
		glm/gtx/intersect.inl \
		glm/gtx/log_base.hpp \
		glm/gtx/log_base.inl \
		glm/gtx/matrix_cross_product.hpp \
		glm/gtx/matrix_cross_product.inl \
		glm/gtx/matrix_interpolation.hpp \
		glm/gtx/matrix_interpolation.inl \
		glm/gtx/matrix_major_storage.hpp \
		glm/gtx/matrix_major_storage.inl \
		glm/gtx/matrix_operation.hpp \
		glm/gtx/matrix_operation.inl \
		glm/gtx/matrix_query.hpp \
		glm/gtx/matrix_query.inl \
		glm/gtx/mixed_product.hpp \
		glm/gtx/mixed_product.inl \
		glm/gtx/norm.hpp \
		glm/gtx/quaternion.hpp \
		glm/gtx/norm.inl \
		glm/gtx/normal.hpp \
		glm/gtx/normal.inl \
		glm/gtx/normalize_dot.hpp \
		glm/gtx/normalize_dot.inl \
		glm/gtx/number_precision.hpp \
		glm/gtx/number_precision.inl \
		glm/gtx/orthonormalize.hpp \
		glm/gtx/orthonormalize.inl \
		glm/gtx/perpendicular.hpp \
		glm/gtx/projection.hpp \
		glm/gtx/projection.inl \
		glm/gtx/perpendicular.inl \
		glm/gtx/polar_coordinates.hpp \
		glm/gtx/polar_coordinates.inl \
		glm/gtx/raw_data.hpp \
		glm/gtx/raw_data.inl \
		glm/gtx/rotate_vector.hpp \
		glm/gtx/transform.hpp \
		glm/gtx/transform.inl \
		glm/gtx/rotate_vector.inl \
		glm/gtx/spline.hpp \
		glm/gtx/spline.inl \
		glm/gtx/std_based_type.hpp \
		glm/gtx/std_based_type.inl \
		glm/gtx/transform2.hpp \
		glm/gtx/transform2.inl \
		glm/gtx/vector_angle.hpp \
		glm/gtx/vector_angle.inl \
		glm/gtx/wrap.hpp \
		glm/gtx/wrap.inl \
		glm/gtx/scalar_multiplication.hpp \
		glm/gtx/range.hpp \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		include/GLWindow.h \
		moc/moc_predefs.h \
		../Qt/5.9.1/clang_64/bin/moc
	/Users/albertolascala/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/Users/albertolascala/Qt/5.9.1/clang_64/mkspecs/macx-clang -I/Users/albertolascala/TexSketch -I/Users/albertolascala/TexSketch/include -I/Users/albertolascala/TexSketch/ui -I/Users/albertolascala/TexSketch/glm -I/Users/albertolascala/TexSketch/shaders -I/Users/albertolascala/TexSketch/images -I/Users/albertolascala/Qt/5.9.1/clang_64/lib/QtOpenGL.framework/Headers -I/Users/albertolascala/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/albertolascala/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/albertolascala/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/usr/local/include/c++/6.4.0 -I/usr/local/include/c++/6.4.0/x86_64-pc-linux-gnu -I/usr/local/include/c++/6.4.0/backward -I/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include -I/usr/local/include -I/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include-fixed -I/usr/include -F/Users/albertolascala/Qt/5.9.1/clang_64/lib include/GLWindow.h -o moc/moc_GLWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/ui_MainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui/ui_MainWindow.h
ui/ui_MainWindow.h: ui/MainWindow.ui \
		../Qt/5.9.1/clang_64/bin/uic
	/Users/albertolascala/Qt/5.9.1/clang_64/bin/uic ui/MainWindow.ui -o ui/ui_MainWindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/main.o: src/main.cpp ../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		include/MainWindow.h \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		include/GLWindow.h \
		include/Shader.h \
		include/TrackballCamera.h \
		include/Camera.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/detail/func_matrix.hpp \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/detail/func_exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/exponential.hpp \
		glm/common.hpp \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/matrix.hpp \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/matrix_transform.inl \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/quaternion.inl \
		glm/gtc/quaternion_simd.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QEvent \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		include/Mesh.h \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		glm/ext.hpp \
		glm/gtc/bitfield.hpp \
		glm/gtc/bitfield.inl \
		glm/gtc/color_space.hpp \
		glm/gtc/color_space.inl \
		glm/gtc/epsilon.hpp \
		glm/gtc/epsilon.inl \
		glm/gtc/functions.hpp \
		glm/gtc/functions.inl \
		glm/gtc/integer.hpp \
		glm/gtc/integer.inl \
		glm/gtc/matrix_access.hpp \
		glm/gtc/matrix_access.inl \
		glm/gtc/matrix_integer.hpp \
		glm/gtc/matrix_inverse.hpp \
		glm/gtc/matrix_inverse.inl \
		glm/gtc/noise.hpp \
		glm/detail/_noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/packing.hpp \
		glm/gtc/packing.inl \
		glm/gtc/random.hpp \
		glm/gtc/random.inl \
		glm/gtc/reciprocal.hpp \
		glm/gtc/reciprocal.inl \
		glm/gtc/round.hpp \
		glm/gtc/round.inl \
		glm/gtc/ulp.hpp \
		glm/gtc/ulp.inl \
		glm/gtc/type_aligned.hpp \
		glm/gtx/associated_min_max.hpp \
		glm/gtx/associated_min_max.inl \
		glm/gtx/bit.hpp \
		glm/gtx/bit.inl \
		glm/gtx/closest_point.hpp \
		glm/gtx/closest_point.inl \
		glm/gtx/color_space.hpp \
		glm/gtx/color_space_YCoCg.hpp \
		glm/gtx/color_space_YCoCg.inl \
		glm/gtx/compatibility.hpp \
		glm/gtx/compatibility.inl \
		glm/gtx/component_wise.hpp \
		glm/gtx/component_wise.inl \
		glm/gtx/euler_angles.hpp \
		glm/gtx/euler_angles.inl \
		glm/gtx/extend.hpp \
		glm/gtx/extend.inl \
		glm/gtx/extended_min_max.hpp \
		glm/gtx/extended_min_max.inl \
		glm/gtx/fast_exponential.hpp \
		glm/gtx/fast_exponential.inl \
		glm/gtx/fast_square_root.hpp \
		glm/gtx/fast_square_root.inl \
		glm/gtx/fast_trigonometry.hpp \
		glm/gtx/fast_trigonometry.inl \
		glm/gtx/gradient_paint.hpp \
		glm/gtx/optimum_pow.hpp \
		glm/gtx/optimum_pow.inl \
		glm/gtx/gradient_paint.inl \
		glm/gtx/handed_coordinate_space.hpp \
		glm/gtx/handed_coordinate_space.inl \
		glm/gtx/integer.hpp \
		glm/gtx/intersect.hpp \
		glm/gtx/vector_query.hpp \
		glm/gtx/vector_query.inl \
		glm/gtx/intersect.inl \
		glm/gtx/log_base.hpp \
		glm/gtx/log_base.inl \
		glm/gtx/matrix_cross_product.hpp \
		glm/gtx/matrix_cross_product.inl \
		glm/gtx/matrix_interpolation.hpp \
		glm/gtx/matrix_interpolation.inl \
		glm/gtx/matrix_major_storage.hpp \
		glm/gtx/matrix_major_storage.inl \
		glm/gtx/matrix_operation.hpp \
		glm/gtx/matrix_operation.inl \
		glm/gtx/matrix_query.hpp \
		glm/gtx/matrix_query.inl \
		glm/gtx/mixed_product.hpp \
		glm/gtx/mixed_product.inl \
		glm/gtx/norm.hpp \
		glm/gtx/quaternion.hpp \
		glm/gtx/norm.inl \
		glm/gtx/normal.hpp \
		glm/gtx/normal.inl \
		glm/gtx/normalize_dot.hpp \
		glm/gtx/normalize_dot.inl \
		glm/gtx/number_precision.hpp \
		glm/gtx/number_precision.inl \
		glm/gtx/orthonormalize.hpp \
		glm/gtx/orthonormalize.inl \
		glm/gtx/perpendicular.hpp \
		glm/gtx/projection.hpp \
		glm/gtx/projection.inl \
		glm/gtx/perpendicular.inl \
		glm/gtx/polar_coordinates.hpp \
		glm/gtx/polar_coordinates.inl \
		glm/gtx/raw_data.hpp \
		glm/gtx/raw_data.inl \
		glm/gtx/rotate_vector.hpp \
		glm/gtx/transform.hpp \
		glm/gtx/transform.inl \
		glm/gtx/rotate_vector.inl \
		glm/gtx/spline.hpp \
		glm/gtx/spline.inl \
		glm/gtx/std_based_type.hpp \
		glm/gtx/std_based_type.inl \
		glm/gtx/transform2.hpp \
		glm/gtx/transform2.inl \
		glm/gtx/vector_angle.hpp \
		glm/gtx/vector_angle.inl \
		glm/gtx/wrap.hpp \
		glm/gtx/wrap.inl \
		glm/gtx/scalar_multiplication.hpp \
		glm/gtx/range.hpp \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/MainWindow.o: src/MainWindow.cpp include/MainWindow.h \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		include/GLWindow.h \
		include/Shader.h \
		include/TrackballCamera.h \
		include/Camera.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/detail/func_matrix.hpp \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/detail/func_exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/exponential.hpp \
		glm/common.hpp \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/matrix.hpp \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/matrix_transform.inl \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/quaternion.inl \
		glm/gtc/quaternion_simd.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QEvent \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		include/Mesh.h \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		glm/ext.hpp \
		glm/gtc/bitfield.hpp \
		glm/gtc/bitfield.inl \
		glm/gtc/color_space.hpp \
		glm/gtc/color_space.inl \
		glm/gtc/epsilon.hpp \
		glm/gtc/epsilon.inl \
		glm/gtc/functions.hpp \
		glm/gtc/functions.inl \
		glm/gtc/integer.hpp \
		glm/gtc/integer.inl \
		glm/gtc/matrix_access.hpp \
		glm/gtc/matrix_access.inl \
		glm/gtc/matrix_integer.hpp \
		glm/gtc/matrix_inverse.hpp \
		glm/gtc/matrix_inverse.inl \
		glm/gtc/noise.hpp \
		glm/detail/_noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/packing.hpp \
		glm/gtc/packing.inl \
		glm/gtc/random.hpp \
		glm/gtc/random.inl \
		glm/gtc/reciprocal.hpp \
		glm/gtc/reciprocal.inl \
		glm/gtc/round.hpp \
		glm/gtc/round.inl \
		glm/gtc/ulp.hpp \
		glm/gtc/ulp.inl \
		glm/gtc/type_aligned.hpp \
		glm/gtx/associated_min_max.hpp \
		glm/gtx/associated_min_max.inl \
		glm/gtx/bit.hpp \
		glm/gtx/bit.inl \
		glm/gtx/closest_point.hpp \
		glm/gtx/closest_point.inl \
		glm/gtx/color_space.hpp \
		glm/gtx/color_space_YCoCg.hpp \
		glm/gtx/color_space_YCoCg.inl \
		glm/gtx/compatibility.hpp \
		glm/gtx/compatibility.inl \
		glm/gtx/component_wise.hpp \
		glm/gtx/component_wise.inl \
		glm/gtx/euler_angles.hpp \
		glm/gtx/euler_angles.inl \
		glm/gtx/extend.hpp \
		glm/gtx/extend.inl \
		glm/gtx/extended_min_max.hpp \
		glm/gtx/extended_min_max.inl \
		glm/gtx/fast_exponential.hpp \
		glm/gtx/fast_exponential.inl \
		glm/gtx/fast_square_root.hpp \
		glm/gtx/fast_square_root.inl \
		glm/gtx/fast_trigonometry.hpp \
		glm/gtx/fast_trigonometry.inl \
		glm/gtx/gradient_paint.hpp \
		glm/gtx/optimum_pow.hpp \
		glm/gtx/optimum_pow.inl \
		glm/gtx/gradient_paint.inl \
		glm/gtx/handed_coordinate_space.hpp \
		glm/gtx/handed_coordinate_space.inl \
		glm/gtx/integer.hpp \
		glm/gtx/intersect.hpp \
		glm/gtx/vector_query.hpp \
		glm/gtx/vector_query.inl \
		glm/gtx/intersect.inl \
		glm/gtx/log_base.hpp \
		glm/gtx/log_base.inl \
		glm/gtx/matrix_cross_product.hpp \
		glm/gtx/matrix_cross_product.inl \
		glm/gtx/matrix_interpolation.hpp \
		glm/gtx/matrix_interpolation.inl \
		glm/gtx/matrix_major_storage.hpp \
		glm/gtx/matrix_major_storage.inl \
		glm/gtx/matrix_operation.hpp \
		glm/gtx/matrix_operation.inl \
		glm/gtx/matrix_query.hpp \
		glm/gtx/matrix_query.inl \
		glm/gtx/mixed_product.hpp \
		glm/gtx/mixed_product.inl \
		glm/gtx/norm.hpp \
		glm/gtx/quaternion.hpp \
		glm/gtx/norm.inl \
		glm/gtx/normal.hpp \
		glm/gtx/normal.inl \
		glm/gtx/normalize_dot.hpp \
		glm/gtx/normalize_dot.inl \
		glm/gtx/number_precision.hpp \
		glm/gtx/number_precision.inl \
		glm/gtx/orthonormalize.hpp \
		glm/gtx/orthonormalize.inl \
		glm/gtx/perpendicular.hpp \
		glm/gtx/projection.hpp \
		glm/gtx/projection.inl \
		glm/gtx/perpendicular.inl \
		glm/gtx/polar_coordinates.hpp \
		glm/gtx/polar_coordinates.inl \
		glm/gtx/raw_data.hpp \
		glm/gtx/raw_data.inl \
		glm/gtx/rotate_vector.hpp \
		glm/gtx/transform.hpp \
		glm/gtx/transform.inl \
		glm/gtx/rotate_vector.inl \
		glm/gtx/spline.hpp \
		glm/gtx/spline.inl \
		glm/gtx/std_based_type.hpp \
		glm/gtx/std_based_type.inl \
		glm/gtx/transform2.hpp \
		glm/gtx/transform2.inl \
		glm/gtx/vector_angle.hpp \
		glm/gtx/vector_angle.inl \
		glm/gtx/wrap.hpp \
		glm/gtx/wrap.inl \
		glm/gtx/scalar_multiplication.hpp \
		glm/gtx/range.hpp \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		ui/ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MainWindow.o src/MainWindow.cpp

obj/GLWindow.o: src/GLWindow.cpp include/GLWindow.h \
		include/Shader.h \
		include/TrackballCamera.h \
		include/Camera.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/detail/func_matrix.hpp \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/detail/func_exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/exponential.hpp \
		glm/common.hpp \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/matrix.hpp \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/matrix_transform.inl \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/quaternion.inl \
		glm/gtc/quaternion_simd.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QEvent \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		include/Mesh.h \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		glm/ext.hpp \
		glm/gtc/bitfield.hpp \
		glm/gtc/bitfield.inl \
		glm/gtc/color_space.hpp \
		glm/gtc/color_space.inl \
		glm/gtc/epsilon.hpp \
		glm/gtc/epsilon.inl \
		glm/gtc/functions.hpp \
		glm/gtc/functions.inl \
		glm/gtc/integer.hpp \
		glm/gtc/integer.inl \
		glm/gtc/matrix_access.hpp \
		glm/gtc/matrix_access.inl \
		glm/gtc/matrix_integer.hpp \
		glm/gtc/matrix_inverse.hpp \
		glm/gtc/matrix_inverse.inl \
		glm/gtc/noise.hpp \
		glm/detail/_noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/packing.hpp \
		glm/gtc/packing.inl \
		glm/gtc/random.hpp \
		glm/gtc/random.inl \
		glm/gtc/reciprocal.hpp \
		glm/gtc/reciprocal.inl \
		glm/gtc/round.hpp \
		glm/gtc/round.inl \
		glm/gtc/ulp.hpp \
		glm/gtc/ulp.inl \
		glm/gtc/type_aligned.hpp \
		glm/gtx/associated_min_max.hpp \
		glm/gtx/associated_min_max.inl \
		glm/gtx/bit.hpp \
		glm/gtx/bit.inl \
		glm/gtx/closest_point.hpp \
		glm/gtx/closest_point.inl \
		glm/gtx/color_space.hpp \
		glm/gtx/color_space_YCoCg.hpp \
		glm/gtx/color_space_YCoCg.inl \
		glm/gtx/compatibility.hpp \
		glm/gtx/compatibility.inl \
		glm/gtx/component_wise.hpp \
		glm/gtx/component_wise.inl \
		glm/gtx/euler_angles.hpp \
		glm/gtx/euler_angles.inl \
		glm/gtx/extend.hpp \
		glm/gtx/extend.inl \
		glm/gtx/extended_min_max.hpp \
		glm/gtx/extended_min_max.inl \
		glm/gtx/fast_exponential.hpp \
		glm/gtx/fast_exponential.inl \
		glm/gtx/fast_square_root.hpp \
		glm/gtx/fast_square_root.inl \
		glm/gtx/fast_trigonometry.hpp \
		glm/gtx/fast_trigonometry.inl \
		glm/gtx/gradient_paint.hpp \
		glm/gtx/optimum_pow.hpp \
		glm/gtx/optimum_pow.inl \
		glm/gtx/gradient_paint.inl \
		glm/gtx/handed_coordinate_space.hpp \
		glm/gtx/handed_coordinate_space.inl \
		glm/gtx/integer.hpp \
		glm/gtx/intersect.hpp \
		glm/gtx/vector_query.hpp \
		glm/gtx/vector_query.inl \
		glm/gtx/intersect.inl \
		glm/gtx/log_base.hpp \
		glm/gtx/log_base.inl \
		glm/gtx/matrix_cross_product.hpp \
		glm/gtx/matrix_cross_product.inl \
		glm/gtx/matrix_interpolation.hpp \
		glm/gtx/matrix_interpolation.inl \
		glm/gtx/matrix_major_storage.hpp \
		glm/gtx/matrix_major_storage.inl \
		glm/gtx/matrix_operation.hpp \
		glm/gtx/matrix_operation.inl \
		glm/gtx/matrix_query.hpp \
		glm/gtx/matrix_query.inl \
		glm/gtx/mixed_product.hpp \
		glm/gtx/mixed_product.inl \
		glm/gtx/norm.hpp \
		glm/gtx/quaternion.hpp \
		glm/gtx/norm.inl \
		glm/gtx/normal.hpp \
		glm/gtx/normal.inl \
		glm/gtx/normalize_dot.hpp \
		glm/gtx/normalize_dot.inl \
		glm/gtx/number_precision.hpp \
		glm/gtx/number_precision.inl \
		glm/gtx/orthonormalize.hpp \
		glm/gtx/orthonormalize.inl \
		glm/gtx/perpendicular.hpp \
		glm/gtx/projection.hpp \
		glm/gtx/projection.inl \
		glm/gtx/perpendicular.inl \
		glm/gtx/polar_coordinates.hpp \
		glm/gtx/polar_coordinates.inl \
		glm/gtx/raw_data.hpp \
		glm/gtx/raw_data.inl \
		glm/gtx/rotate_vector.hpp \
		glm/gtx/transform.hpp \
		glm/gtx/transform.inl \
		glm/gtx/rotate_vector.inl \
		glm/gtx/spline.hpp \
		glm/gtx/spline.inl \
		glm/gtx/std_based_type.hpp \
		glm/gtx/std_based_type.inl \
		glm/gtx/transform2.hpp \
		glm/gtx/transform2.inl \
		glm/gtx/vector_angle.hpp \
		glm/gtx/vector_angle.inl \
		glm/gtx/wrap.hpp \
		glm/gtx/wrap.inl \
		glm/gtx/scalar_multiplication.hpp \
		glm/gtx/range.hpp \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QColorDialog \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../Qt/5.9.1/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../Qt/5.9.1/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QColor \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qcolor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GLWindow.o src/GLWindow.cpp

obj/Mesh.o: src/Mesh.cpp include/Mesh.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/detail/func_matrix.hpp \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/detail/func_exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/exponential.hpp \
		glm/common.hpp \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/matrix.hpp \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Mesh.o src/Mesh.cpp

obj/Shader.o: src/Shader.cpp include/Shader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Shader.o src/Shader.cpp

obj/Camera.o: src/Camera.cpp include/Camera.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/detail/func_matrix.hpp \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/detail/func_exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/exponential.hpp \
		glm/common.hpp \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/matrix.hpp \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/matrix_transform.inl \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/quaternion.inl \
		glm/gtc/quaternion_simd.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Camera.o src/Camera.cpp

obj/TrackballCamera.o: src/TrackballCamera.cpp include/TrackballCamera.h \
		include/Camera.h \
		glm/glm.hpp \
		glm/detail/_fixes.hpp \
		glm/fwd.hpp \
		glm/detail/type_int.hpp \
		glm/detail/setup.hpp \
		glm/simd/platform.h \
		glm/detail/type_float.hpp \
		glm/detail/type_vec.hpp \
		glm/detail/precision.hpp \
		glm/detail/type_mat.hpp \
		glm/vec2.hpp \
		glm/detail/type_vec2.hpp \
		glm/detail/_swizzle.hpp \
		glm/detail/_swizzle_func.hpp \
		glm/detail/type_vec2.inl \
		glm/vec3.hpp \
		glm/detail/type_vec3.hpp \
		glm/detail/type_vec3.inl \
		glm/vec4.hpp \
		glm/detail/type_vec4.hpp \
		glm/detail/type_vec4.inl \
		glm/detail/type_vec4_simd.inl \
		glm/mat2x2.hpp \
		glm/detail/type_mat2x2.hpp \
		glm/detail/type_mat2x2.inl \
		glm/detail/func_matrix.hpp \
		glm/mat2x3.hpp \
		glm/detail/type_mat2x3.hpp \
		glm/detail/type_mat2x3.inl \
		glm/mat2x4.hpp \
		glm/detail/type_mat2x4.hpp \
		glm/detail/type_mat2x4.inl \
		glm/mat3x2.hpp \
		glm/detail/type_mat3x2.hpp \
		glm/detail/type_mat3x2.inl \
		glm/mat3x3.hpp \
		glm/detail/type_mat3x3.hpp \
		glm/detail/type_mat3x3.inl \
		glm/mat3x4.hpp \
		glm/detail/type_mat3x4.hpp \
		glm/detail/type_mat3x4.inl \
		glm/mat4x2.hpp \
		glm/detail/type_mat4x2.hpp \
		glm/detail/type_mat4x2.inl \
		glm/mat4x3.hpp \
		glm/detail/type_mat4x3.hpp \
		glm/detail/type_mat4x3.inl \
		glm/mat4x4.hpp \
		glm/detail/type_mat4x4.hpp \
		glm/detail/type_mat4x4.inl \
		glm/detail/type_mat4x4_simd.inl \
		glm/detail/func_matrix.inl \
		glm/geometric.hpp \
		glm/detail/func_geometric.hpp \
		glm/detail/func_geometric.inl \
		glm/detail/func_exponential.hpp \
		glm/detail/type_vec1.hpp \
		glm/detail/type_vec1.inl \
		glm/detail/func_exponential.inl \
		glm/detail/func_vector_relational.hpp \
		glm/detail/func_vector_relational.inl \
		glm/detail/func_vector_relational_simd.inl \
		glm/detail/_vectorize.hpp \
		glm/detail/func_exponential_simd.inl \
		glm/simd/exponential.h \
		glm/detail/func_common.hpp \
		glm/detail/func_common.inl \
		glm/detail/func_common_simd.inl \
		glm/simd/common.h \
		glm/detail/func_geometric_simd.inl \
		glm/simd/geometric.h \
		glm/detail/func_matrix_simd.inl \
		glm/simd/matrix.h \
		glm/trigonometric.hpp \
		glm/detail/func_trigonometric.hpp \
		glm/detail/func_trigonometric.inl \
		glm/detail/func_trigonometric_simd.inl \
		glm/exponential.hpp \
		glm/common.hpp \
		glm/packing.hpp \
		glm/detail/func_packing.hpp \
		glm/detail/func_packing.inl \
		glm/detail/type_half.hpp \
		glm/detail/type_half.inl \
		glm/detail/func_packing_simd.inl \
		glm/matrix.hpp \
		glm/vector_relational.hpp \
		glm/integer.hpp \
		glm/detail/func_integer.hpp \
		glm/detail/func_integer.inl \
		glm/detail/func_integer_simd.inl \
		glm/simd/integer.h \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/matrix_transform.inl \
		glm/gtx/string_cast.hpp \
		glm/gtc/type_precision.hpp \
		glm/gtc/quaternion.hpp \
		glm/gtc/quaternion.inl \
		glm/gtc/quaternion_simd.inl \
		glm/gtc/vec1.hpp \
		glm/gtc/vec1.inl \
		glm/gtc/type_precision.inl \
		glm/gtx/dual_quaternion.hpp \
		glm/gtx/dual_quaternion.inl \
		glm/gtx/string_cast.inl \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QEvent \
		../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QResizeEvent \
		../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		glm/gtx/norm.hpp \
		glm/gtx/quaternion.hpp \
		glm/gtx/norm.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/TrackballCamera.o src/TrackballCamera.cpp

obj/moc_MainWindow.o: moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_MainWindow.o moc/moc_MainWindow.cpp

obj/moc_GLWindow.o: moc/moc_GLWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_GLWindow.o moc/moc_GLWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

